package gui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kferens
 */
public class GUI extends javax.swing.JFrame implements frameworkuserinterface.FrameworkUserInterface {

    String portNumber = "";
    boolean serverSocketStarted = false;
    boolean serverListenStarted = false;
    timeserverusercommandhandler.TimeServerUserCommandHandler myUserCommandHandler;

    /**
     * Creates new form ServerGUIMainWindow
     */
    public GUI() {
        initComponents();
    }

    public void update(String theResult) {
        messageWindow.append(theResult + "\n");
    }

    public void setUserCommandHandler(timeserverusercommandhandler.TimeServerUserCommandHandler myUserCommandHandler) {
        this.myUserCommandHandler = myUserCommandHandler;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        portNumberTextBox = new javax.swing.JTextField();
        portUpdateButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        serverSocketStartButton = new javax.swing.JButton();
        serverSocketStopButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        serverListenStartButton = new javax.swing.JButton();
        serverListenStopButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageWindow = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ServerGUIMainWindow");

        jLabel1.setText("Set Listening Port");

        portNumberTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portNumberTextBoxActionPerformed(evt);
            }
        });

        portUpdateButton.setText("Update");
        portUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portUpdateButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Server Socket");

        serverSocketStartButton.setText("Start");
        serverSocketStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverSocketStartButtonActionPerformed(evt);
            }
        });

        serverSocketStopButton.setText("Stop");
        serverSocketStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverSocketStopButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Listen");

        serverListenStartButton.setText("Start");
        serverListenStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverListenStartButtonActionPerformed(evt);
            }
        });

        serverListenStopButton.setText("Stop");
        serverListenStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverListenStopButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Messages");

        messageWindow.setColumns(20);
        messageWindow.setRows(5);
        jScrollPane1.setViewportView(messageWindow);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(portNumberTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(portUpdateButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(serverListenStartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(serverSocketStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(serverSocketStopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(serverListenStopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(portNumberTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(portUpdateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverSocketStartButton)
                    .addComponent(serverSocketStopButton)
                    .addComponent(jLabel2))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverListenStartButton)
                    .addComponent(serverListenStopButton)
                    .addComponent(jLabel3))
                .addGap(49, 49, 49)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void portUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portUpdateButtonActionPerformed
        portNumber = portNumberTextBox.getText();
        this.myUserCommandHandler.handleUserCommand("3 " + portNumber);
    }//GEN-LAST:event_portUpdateButtonActionPerformed

    private void portNumberTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portNumberTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portNumberTextBoxActionPerformed

    private void serverSocketStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverSocketStartButtonActionPerformed
        this.myUserCommandHandler.handleUserCommand("6");
    }//GEN-LAST:event_serverSocketStartButtonActionPerformed

    private void serverSocketStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverSocketStopButtonActionPerformed
        messageWindow.append("Closing the server socket command has not been implemented yet.\n");
    }//GEN-LAST:event_serverSocketStopButtonActionPerformed

    private void serverListenStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverListenStartButtonActionPerformed
        this.myUserCommandHandler.handleUserCommand("2");
    }//GEN-LAST:event_serverListenStartButtonActionPerformed

    private void serverListenStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverListenStopButtonActionPerformed
        messageWindow.append("Server listening stop command has not beeen implemented yet\n");
    }//GEN-LAST:event_serverListenStopButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messageWindow;
    private javax.swing.JTextField portNumberTextBox;
    private javax.swing.JButton portUpdateButton;
    private javax.swing.JButton serverListenStartButton;
    private javax.swing.JButton serverListenStopButton;
    private javax.swing.JButton serverSocketStartButton;
    private javax.swing.JButton serverSocketStopButton;
    // End of variables declaration//GEN-END:variables

}
